---
name: python package
on:
  push:
    tags:
      - '*'
jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: install nox
        run: pip install nox
      - name: run nox
        run: nox -s pack
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/kenallclient-*.whl
            dist/kenallclient-*.tar.gz
            dist/kenallclient-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
